### ISSUE TITLE
Fail while sync Gradle

### ISSUE THREAD

**Issue by khoana56** [crysxd/CameraX-Object-Tracking#1]
When I copy the code: "implementation 'com.github.crysxd:CameraX-Object-Tracking:latest-version'" and paste into the build.gradle (app), then select "sync now" and it show this.

![image](https://user-images.githubusercontent.com/38883688/69854865-c1098680-12bc-11ea-9ba5-84f6bb4fd248.png)

Can you show me how to fix this?
Thank you very much!

**Comment by crysxd** [comment]
You have to replace 'latest-version' with the actual version number. This is currently 1.3.

**Comment by khoana56** [comment]
Thank you! I got it

*Best Regard!*
*----------------------------------------------------*
*Nguyễn Anh Khoa*
*Học viện Công nghệ Bưu chính Viễn thông (Cơ sở tại TP. HCM)*
*Phone: 077 378 4824*
*Email: khoanguyen.ptithcm@gmail.com <khoanguyen.ptithcm@gmail.com>*
